name: Publish

on:
  push:
    tags:
      - '*'

env:
  CONFIG_FILE: jsr.json

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout with tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: get version information
        id: vars
        run: |
          echo "JSR_VERSION=$(npx strip-json-comments-cli $CONFIG_FILE | jq -rM '.version')" >> $GITHUB_OUTPUT
          echo ${{ github.ref_name }} | perl -ne '$_ =~ /((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$/; printf("TAG_VERSION=$1");' >> $GITHUB_OUTPUT

      - name: publish to JSR
        if: ${{ steps.vars.outputs.JSR_VERSION == steps.vars.outputs.TAG_VERSION }}
        run: npx jsr publish --config $CONFIG_FILE
